services:

  express-app:
    image: zebrasino/express-app:latest
    container_name: express-app
    ports:
      - 9000:9000
    restart: always
    
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - DOCKER_API_VERSION=1.45
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - express-app
    